# Step 1: Use the official Node.js image as the base image
FROM node:lts

# Step 2: Set the working directory inside the container
WORKDIR /app

# Step 3: Copy the package.json and package-lock.json files to the working directory
COPY package*.json ./

# Step 4: Install dependencies
RUN npm install

# Step 5: Copy the rest of the application files to the working directory
COPY . .

# Step 6: Expose port 5000
EXPOSE 80

# RUN npm run build

# Step 7: Start the application
CMD ["npm", "run","dev:prisma"]
